version: 1.0.{build}
skip_branch_with_pr: true
image:
  - Visual Studio 2017
  - Ubuntu
install:
  - ps: Install-Module Pester -Force -Scope CurrentUser
build: off
test_script:
  - ps: |
      Set-StrictMode -Version 3.0
      Invoke-Pester -EnableExit -OutputFile Tests.xml -OutputFormat NUnitXml
      [System.Net.WebClient]::new().UploadFile("https://ci.appveyor.com/api/testresults/nunit/${env:APPVEYOR_JOB_ID}", (Join-Path $PWD 'Tests.xml'))
